// import { createClient } from "@supabase/supabase-js";
//
// const SUPABASE_URL = "https://kiectcpzqkevyzrkwyin.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY =
//   "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpZWN0Y3B6cWtldnl6cmt3eWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4NTIwMDEsImV4cCI6MjA4NjQyODAwMX0.Hh5G8uKRLHpMYV2DhG0LKA8b7Wk66A4TpZYiFTPbi8o";
//
// export const supabase = createClient(
//   SUPABASE_URL,
//   SUPABASE_PUBLISHABLE_KEY,
//   {
//     auth: {
//       storage:
//         typeof window !== "undefined" ? window.localStorage : undefined,
//       persistSession: true,
//       autoRefreshToken: true,
//     },
//   }
// );
// // This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

const SUPABASE_URL = "https://kiectcpzqkevyzrkwyin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpZWN0Y3B6cWtldnl6cmt3eWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4NTIwMDEsImV4cCI6MjA4NjQyODAwMX0.Hh5G8uKRLHpMYV2DhG0LKA8b7Wk66A4TpZYiFTPbi8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
